/**
 * Sync build assets into the suite package:
 *   ../catalog/*.json        -> catalog/         (eac/aio/skins/community/retired)
 *   ../dist/*                -> assets/dist/     (repacked tarballs + index + checksums,
 *                                                 pruned to match dist/ exactly)
 *   ../suite/assets/gallery.json + previews/ + prompts/
 *                            -> managed skin-gallery assets (generated by
 *                               scripts/fetch-assets.mjs): presence-checked and
 *                               pkgVersion-validated against the freshly synced
 *                               catalog; forward-compat copy from a repo-root
 *                               assets/ staging dir when one is provided.
 *
 * Run before `npm pack` of the suite so the published tarball is fully
 * offline-capable. Fails loudly when the catalog is missing but never blocks
 * on dist absence (dev mode still works against registry specs).
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..')
const suite = path.join(root, 'suite')
const catalogOut = path.join(suite, 'catalog')
const distOut = path.join(suite, 'assets', 'dist')
const galleryFile = path.join(suite, 'assets', 'gallery.json')

for (const pack of ['eac', 'aio', 'skins', 'community', 'retired']) {
  const src = path.join(root, 'catalog', `${pack}.json`)
  if (!fs.existsSync(src)) {
    if (pack === 'retired') continue
    console.error(`[sync] missing catalog/${pack}.json — run the asset pipeline first`)
    process.exitCode = 1
    continue
  }
  fs.mkdirSync(catalogOut, { recursive: true })
  fs.copyFileSync(src, path.join(catalogOut, `${pack}.json`))
  console.log(`[sync] catalog/${pack}.json`)
}

if (fs.existsSync(path.join(root, 'dist'))) {
  fs.mkdirSync(distOut, { recursive: true })
  const wanted = new Set()
  for (const name of fs.readdirSync(path.join(root, 'dist'))) {
    if (!/\.(tgz|json|txt|md)$/.test(name)) continue
    wanted.add(name)
    fs.copyFileSync(path.join(root, 'dist', name), path.join(distOut, name))
  }
  // prune stale copies so suite/assets/dist mirrors dist/ exactly
  let pruned = 0
  for (const name of fs.readdirSync(distOut)) {
    if (!wanted.has(name)) {
      fs.rmSync(path.join(distOut, name), { force: true })
      pruned++
    }
  }
  const n = fs.readdirSync(distOut).filter((f) => f.endsWith('.tgz')).length
  console.log(`[sync] assets/dist: ${n} tarballs copied${pruned ? `, ${pruned} stale pruned` : ''}`)
} else {
  console.warn('[sync] dist/ not present — suite will fall back to registry specs')
}

// ---- skin-gallery assets（fetch-assets.mjs 产物）----
// 仓库根若提供 assets/ 暂存目录则先拷入（前向兼容）；随后做存在性与一致性校验。
const rootStage = path.join(root, 'assets')
if (fs.existsSync(path.join(rootStage, 'gallery.json'))) {
  fs.copyFileSync(path.join(rootStage, 'gallery.json'), galleryFile)
  console.log('[sync] assets/gallery.json (from repo-root staging)')
  for (const dir of ['previews', 'prompts']) {
    const srcDir = path.join(rootStage, dir)
    const outDir = path.join(suite, 'assets', dir)
    if (!fs.existsSync(srcDir)) continue
    fs.mkdirSync(outDir, { recursive: true })
    for (const id of fs.readdirSync(srcDir)) {
      fs.cpSync(path.join(srcDir, id), path.join(outDir, id), { recursive: true })
    }
    console.log(`[sync] assets/${dir} (from repo-root staging)`)
  }
}

let galleryOk = true
if (!fs.existsSync(galleryFile)) {
  console.warn('[sync] assets/gallery.json missing — run `node scripts/fetch-assets.mjs` first')
  galleryOk = false
} else {
  const gallery = JSON.parse(fs.readFileSync(galleryFile, 'utf8'))
  const catalogVersions = new Map()
  for (const pack of ['skins', 'community']) {
    const file = path.join(catalogOut, `${pack}.json`)
    if (!fs.existsSync(file)) continue
    for (const entry of JSON.parse(fs.readFileSync(file, 'utf8'))) {
      catalogVersions.set(entry.id, { version: entry.version, name: entry.name, origin: pack === 'skins' ? 'builtin' : 'community' })
    }
  }
  const missingPreviews = []
  for (const skin of gallery.skins ?? []) {
    const cat = catalogVersions.get(skin.id)
    if (!cat) {
      console.error(`[sync] gallery.json 含未知皮肤 id: ${skin.id}`)
      galleryOk = false
      continue
    }
    if (skin.pkgVersion !== cat.version || skin.pkgName !== cat.name || skin.origin !== cat.origin) {
      console.error(
        `[sync] gallery.json ${skin.id} 与 catalog 不一致: ` +
          `pkg ${skin.pkgName}@${skin.pkgVersion}(${skin.origin}) vs catalog ${cat.name}@${cat.version}(${cat.origin})`,
      )
      galleryOk = false
    }
    for (const key of ['light', 'dark']) {
      const p = skin.previews?.[key]
      if (p && !fs.existsSync(path.join(suite, 'assets', p))) missingPreviews.push(`${skin.id}/${key}`)
    }
    if (skin.prompt && !fs.existsSync(path.join(suite, 'assets', skin.prompt))) missingPreviews.push(`${skin.id}/prompt`)
  }
  if (missingPreviews.length) {
    console.error(`[sync] gallery.json 引用的资产缺失: ${missingPreviews.join(', ')}`)
    galleryOk = false
  }
  const ids = new Set((gallery.skins ?? []).map((s) => s.id))
  for (const [id] of catalogVersions) {
    if (!ids.has(id)) {
      console.error(`[sync] gallery.json 缺少 catalog 皮肤: ${id}`)
      galleryOk = false
    }
  }
  if (galleryOk) {
    const nPrev = fs.existsSync(path.join(suite, 'assets', 'previews'))
      ? fs.readdirSync(path.join(suite, 'assets', 'previews')).length
      : 0
    const nPrompt = fs.existsSync(path.join(suite, 'assets', 'prompts'))
      ? fs.readdirSync(path.join(suite, 'assets', 'prompts')).length
      : 0
    console.log(`[sync] assets/gallery.json: ${gallery.skins.length} skins, previews ${nPrev} ids, prompts ${nPrompt} ids — 与 catalog 一致`)
  }
}
if (!galleryOk) process.exitCode = 1
